### ISSUE TITLE
gsi と Oceanus マージ用のタイルを作成

### ISSUE THREAD

**Issue by naogify** [geolonia/gsi#15]
Oceanus マージ時に z8未満で日本近海が空白になる問題が発生する。

~v1 の `water`, `waterway`, `water_name` レイヤーを `japan-poi-only` タイルに追加した gsi 用のタイルを作成して解決する。~

- https://tileserver.geolonia.com/japan-poi-only/tiles.json
- https://tileserver.geolonia.com/v1/tiles.json

**Comment by keichan34** [comment]
@naogify 今 poi-only に `place` `poi` `aerodrome_label` が入ってるんですが、追加する必要があるレイヤーは `water` `waterway` `water_name` のみで間違いないでしょうか？

**Comment by naogify** [comment]
@keichan34 
すみません！追加するレイヤーを確認中なので少し待ってもらっても良いでしょうか？

**Comment by keichan34** [comment]
はい！タイルを作って欲しいときに教えていただけると :bow:

**Comment by naogify** [comment]
ありがとうございます! min, maxzoom も合わせて確認します。

**Comment by naogify** [comment]
@keichan34 @miya0001 

もう一度確認してみた所、新しくgis マージ用のタイルを作る必要ない事が分かりました。
今ある source の `gsi`、geolonia の `water` `japan-poi-only` で対応可能だったので、issue を閉じますね。


そもそもは zoom8 以上で、日本近海が `gsi` の `water` レイヤー が `oceanus` の `ocean系` レイヤーより優先されて表示されていたのが問題だったのですが、 `gsi` の `water` レイヤーの優先度を下げる事で解決しました。
