### ISSUE TITLE
県庁所在地の表示Zoomレベルにばらつきがある

### ISSUE THREAD

**Issue by ShinichiNishikawa** [geolonia/gsi#19]
Zoom level 6.99

<img width="1156" alt="スクリーンショット 2021-06-21 11 00 01" src="https://user-images.githubusercontent.com/1124652/122697225-d586e880-d27f-11eb-9225-419ae0b828cf.png">

岡山、徳島が出ている。
一方、香川、島根、愛媛は出ていない。

<img width="1157" alt="スクリーンショット 2021-06-21 11 01 36" src="https://user-images.githubusercontent.com/1124652/122697324-0d8e2b80-d280-11eb-8c51-d96b1c46ae7a.png">

**Comment by naogify** [comment]
#20 と共にタイル側（Oceanus）で調整できないか調査してみます!
