### ISSUE TITLE
地下水路が OpenMapTiles のものと地理院のものとで重複している

### ISSUE THREAD

**Issue by kamataryo** [geolonia/gsi#2]
地理院の方はプロパティに水路名が入っていないので悩ましいかも。

<img width="654" alt="Screenshot 2020-05-26 07 51 55" src="https://user-images.githubusercontent.com/6292312/82851198-0c35e680-9f3a-11ea-8e8a-7716969965a1.png">
<img width="886" alt="Screenshot 2020-05-26 07 52 46" src="https://user-images.githubusercontent.com/6292312/82851209-10620400-9f3a-11ea-9b08-1045fe59cc3d.png">

**Comment by kamataryo** [comment]
多くのユーザーは地下水路には関心がないと思うので、地下水路の地物自体を消してしまってもいいのかもしれない。

**Comment by miya0001** [comment]
OSM側の `waterway_tunnel` と `ferry` を削除しました。
https://github.com/geolonia/gsi/commit/d566c93a5356e197eb250dafdb451b3273db0041

一方で地下水路はたしかに消してもいいかもですね。現状の名前の表示位置もおかしいですし、別のIssueを立てて消します。
