### ISSUE TITLE
構造物などの上にあるフェリーターミナルが浮いている

### ISSUE THREAD

**Issue by kamataryo** [geolonia/gsi#5]
<img width="2246" alt="Screenshot 2020-05-26 19 41 53" src="https://user-images.githubusercontent.com/6292312/82892197-04059780-9f8a-11ea-872c-ac65ae5e76b2.png">

**Comment by kamataryo** [comment]
石垣島離島ターミナル。
浮き桟橋が描かれていない。

<img width="816" alt="Screenshot 2020-05-26 19 51 42" src="https://user-images.githubusercontent.com/6292312/82892404-547cf500-9f8a-11ea-8e65-4c87577b6e94.png">

**Comment by miya0001** [comment]
地理院地図Vectorのほうでも出てないですね。
![](https://www.evernote.com/l/ABXxKsAxPstDVpuu8xZbuaIz60HTb8bMiewB/image.png)

以下のスタイルを追加することも考えたけど、よくわからない。

```
    {
      "id": "structurel",
      "type": "line",
      "source": "gsi-japan",
      "source-layer": "structurel",
      "layout": {
        "line-join": "round"
      },
      "paint": {
        "line-color": "#FF0000",
        "line-width": 20
      }
    },
```

![](https://www.evernote.com/l/ABURP2_Zt-5CIKIAJaMk3Eizx43uvy9vAX8B/image.png)

**Comment by miya0001** [comment]
![](https://www.evernote.com/l/ABVYEZzjbJVINpOY-hgLO73dNyLRZ7dBd2AB/image.png)

西表のフェリーターミナルも地理院Vectorの方では出てないっすね。

![](https://www.evernote.com/l/ABVYEZzjbJVINpOY-hgLO73dNyLRZ7dBd2AB/image.png)

というわけで一旦閉じます。
